lib/csgo_stats_web/router.ex
defmodule CsgoStatsWeb.Router do
  use CsgoStatsWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", CsgoStatsWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", GameController, :index)
    get("/parse", PageController, :dump)
    get("/results", PageController, :results)

    resources("/games", GameController, only: [:index, :show])
    resources("/players", PlayerController, only: [:index, :show])
  end

  # Other scopes may use custom stacks.
  # scope "/api", CsgoStatsWeb do
  #   pipe_through :api
  # end
end

lib/csgo_stats/stats/game.ex
defmodule CsgoStats.Stats.Game do
  use Ecto.Schema
  import Ecto.Changeset
  alias CsgoStats.Stats.{TeamGameRecord, PlayerGameRecord, Kill, GameEvent, Assist}

  schema "games" do
    field(:demo_name, :string)
    field(:map_name, :string)
    field(:rounds_played, :integer)
    field(:team1_score, :integer)
    field(:team2_score, :integer)
    field(:tick_rate, :integer)
    field(:major_version, :integer)
    field(:minor_version, :integer)
    field(:patch_version, :integer)
    has_many(:assists, Assist)
    has_many(:game_events, GameEvent)
    has_many(:kills, Kill)
    has_many(:team_game_records, TeamGameRecord)
    has_many(:player_game_records, PlayerGameRecord)
    has_many(:players, through: [:player_game_records, :player])

    timestamps()
  end

  def create_game(game, {teams, filename}) do
    [first_team, second_team] = teams
    first_players = first_team.players
    second_players = second_team.players

    kills =
      List.flatten([first_players, second_players])
      |> Enum.flat_map(fn p -> p.kills end)

    map_name = Enum.at(kills, 0).map_name
    rounds_played = first_team.rounds_won + second_team.rounds_won

    map = %{
      rounds_played: rounds_played,
      team1_score: first_team.rounds_won,
      team2_score: second_team.rounds_won,
      map_name: map_name,
      demo_name: filename
    }

    game
    |> cast(map, [
      :rounds_played,
      :map_name,
      :team1_score,
      :team2_score,
      :rounds_played,
      :demo_name
    ])
    |> validate_required([:map_name, :team1_score, :team2_score, :rounds_played, :demo_name])
    |> unique_constraint([:demo_name])
  end

  @doc false
  def changeset(game, attrs) do
    game
    |> cast(attrs, [
      :map_name,
      :tick_rate,
      :team1_score,
      :team2_score,
      :rounds_played,
      :demo_name,
      :major_version,
      :minor_version,
      :patch_version
    ])
    |> validate_required([
      :map_name,
      :tick_rate,
      :team1_score,
      :team2_score,
      :rounds_played,
      :demo_name,
      :major_version,
      :minor_version,
      :patch_version
    ])
  end
end

lib/csgo_stats_web/controllers/game_controller.ex
defmodule CsgoStatsWeb.GameController do
  use CsgoStatsWeb, :controller

  alias CsgoStats.Stats

  def index(conn, _params) do
    games = Stats.list_games()
    render(conn, "index.html", games: games)
  end

  def show(conn, %{"id" => id}) do
    game =
      Stats.get_game!(id)
      |> Stats.get_game_player_records()
      |> Stats.get_game_kills()

    players_by_team =
      game.player_game_records
      |> Enum.sort_by(fn p -> p.kill_count end, &>=/2)
      |> Enum.group_by(fn p -> p.team_game_record_id end)
      |> Enum.sort_by(fn {teamnum, _} -> teamnum end)

    all_players =
      players_by_team
      |> Enum.flat_map(fn {_, players} -> players end)

    render(
      conn,
      "show.html",
      game: game,
      all_players: all_players,
      players_by_team: players_by_team,
      kills: game.kills
    )
  end

  def duels(conn, %{"id" => id}) do
    game =
      Stats.get_game!(id)
      |> Stats.get_game_player_records()
      |> Stats.get_game_kills()

    kills_by_player =
      game.kills
      |> Enum.group_by(fn k -> k.attacker_name end)

    render(
      conn,
      "show.html",
      game: game,
      players: game.player_game_records,
      kills_by_player: kills_by_player
    )
  end
end

lib/csgo_stats_web/views/game_view.ex
defmodule CsgoStatsWeb.GameView do
  use CsgoStatsWeb, :view

  def title(_template, _assigns) do
    "CSGO GAME STATS"
  end

  def get_kills_by_player(kills) do
    kills |> Enum.group_by(fn k -> k.attacker_id end)
  end

  def get_round_breakdown(kills) do
    kills
    |> Enum.sort_by(fn k -> k.tick end)
    |> Enum.group_by(fn k -> k.round end)
    |> Enum.sort_by(fn {roundnum, _kills} -> roundnum end)
  end

  def format_kill(kill = %CsgoStats.Stats.Kill{}) do
    "#{kill.attacker_name} [#{kill.weapon}#{headshot_string(kill)}] #{kill.victim_name} @ #{
      Float.round(kill.time_elapsed || 0.0, 1)
    }s into the round"
  end

  def headshot_string(kill = %CsgoStats.Stats.Kill{}) do
    if kill.headshot do
      " HS"
    else
      ""
    end
  end

  def date_inserted(game) do
    game.inserted_at
    |> NaiveDateTime.to_date()
    |> Date.to_iso8601()
  end

  def duel_record(player, kills_by_player, all_players) do
    player_kills = Map.get(kills_by_player, player.id)

    all_players
    |> Enum.map(fn p ->
      player_kills_against = get_player_kills_against(player_kills, p.id)

      deaths =
        Map.get(kills_by_player, p.id)
        |> get_player_kills_against(player.id)

      {player_kills_against, deaths, p.name}
    end)
  end

  def short_duel_record(kills, deaths, player_name, victim_name) do
    "#{player_name} #{kills}-#{deaths} #{victim_name}"
  end

  def print_duel_record(kills, deaths) do
    if kills > 0 || deaths > 0 do
      "#{kills} (#{Float.round(kills / (kills + deaths) * 100, 2)}%)"
    else
      "#{kills}"
    end
  end

  def short_player_name(str) do
    cond do
      length(String.graphemes(str)) > 9 -> "#{String.slice(str, 0..9)}.."
      true -> str
    end
  end

  defp get_player_kills_against(player_kills, victim_id) do
    if !player_kills do
      0
    else
      player_kills
      |> Enum.filter(fn k ->
        k.victim_id == victim_id
      end)
      |> length()
    end
  end
end

lib/csgo_stats_web/templates/game/_duels.html.eex
<% kills_by_player = get_kills_by_player(@kills) %>
<h2>Duels</h2>
<div class="table-responsive">
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
        <th></th>
        <%= for {teamnum, players} <- @players_by_team do %>
          <%= for player <- players do %>
            <th><%= short_player_name(player.name) %></th>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= for {teamnum, players} <- @players_by_team do %>
        <%= for player <- players do %>
          <tr>
            <td><%= short_player_name(player.name) %></td>
            <%= for {kills, deaths, victim_name} <- duel_record(player, kills_by_player, @all_players) do %>
              <td class="duel-record" data-toggle="tooltip" data-placement="top" title="<%= short_duel_record(kills, deaths, player.name, victim_name) %>">
                <%= print_duel_record(kills, deaths) %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

lib/csgo_stats_web/templates/game/_round_breakdown.html.eex
<h2>Round Breakdown</h2>
<div class="table-responsive">
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
        <th>Round</th>
        <th>Kills</th>
      </tr>
    </thead>
    <tbody>
      <%= for {round_num, kills} <- get_round_breakdown(@kills) do %>
        <tr>
          <td><%= round_num %></td>
          <td>
            <%= for kill <- kills do %>
              <div><%= format_kill(kill) %></div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

lib/csgo_stats_web/templates/game/edit.html.eex
<h2>Edit Game</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.game_path(@conn, :update, @game)) %>

<span><%= link "Back", to: Routes.game_path(@conn, :index) %></span>

lib/csgo_stats_web/templates/game/index.html.eex
<h2>Games</h2>

<table class="table table-sm">
  <thead class="thead-light">
    <tr>
      <th>Date Added</th>
      <th>Map Name</th>
      <th>Score</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for game <- @games do %>
      <tr>
        <td><%= date_inserted(game) %>
        <td><%= game.map_name %></td>
        <td><%= game.team1_score %> - <%= game.team2_score %></td>

        <td class="text-center">
          <%= link "Show", to: Routes.game_path(@conn, :show, game), class: "btn btn-primary btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/csgo_stats_web/templates/game/new.html.eex
<h2>New Game</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.game_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.game_path(@conn, :index) %></span>

lib/csgo_stats_web/templates/game/show.html.eex
<div class="game-show">
  <h2>Game</h2>

  <div class="game-info">
    <span class="bold">Map name:</span> <%= @game.map_name %>
    <br>
    <span class="bold">Score:</span> <%= @game.team1_score %> - <%= @game.team2_score %>
  </div>
  <div class="table-responsive">
    <table class="table table-sm">
      <%= for {teamnum, players} <- @players_by_team do %>
        <thead class="thead-light">
          <tr>
            <th>Name</th>
            <th>K</th>
            <th>A</th>
            <th>D</th>
            <th>KDR</th>
            <th>FK</th>
            <th>FD</th>
            <th>TK</th>
            <th>HS</th>
            <th>HS%</th>
            <th>ADR</th>
            <th>KAST</th>
          </tr>
        </thead>
        <tbody>
          <%= for player <- players do %>
            <tr>
              <td class="clickable"><a href="<%= Routes.player_path(@conn, :show, player.player_id) %>"><%= player.name %></a></td>
              <td><%= player.kill_count %></td>
              <td><%= player.assist_count %></td>
              <td><%= player.death_count %></td>
              <td><%= player.kill_death_ratio %></td>
              <td><%= player.first_kills %></td>
              <td><%= player.first_deaths %></td>
              <td><%= player.trade_kills %></td>
              <td><%= player.headshot_count %></td>
              <td><%= player.headshot_percentage %>%</td>
              <td><%= player.adr %></td>
              <td><%= player.kast %>%</td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  </div>

  <%= render CsgoStatsWeb.GameView, "_duels.html", players_by_team: @players_by_team, all_players: @all_players, kills: @kills %>
  <%= render CsgoStatsWeb.GameView, "_round_breakdown.html", kills: @kills %>

  <%= link "Back", to: Routes.game_path(@conn, :index), class: "btn btn-primary btn-xs" %>
</div>